[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "VisuaLlama"
version = "0.1"
description = "A Llama-2-powered Conversational, Object-Counting AI Assistant"
authors = [
    {name = "Daethyra, Daemon Carino", email = "dev-daethyra@protonmail.com"}
]
license = { file = "LICENSE" }
readme = "README.md"

[project.scripts]
visuallama = "visuallama.__main__:main"

[tool.poetry]
homepage = "https://github.com/daethyra/VisuaLlama"
repository = "https://github.com/daethyra/VisuaLlama"

[tool.poetry.dependencies]
transformers 
tensorflow 
requests 
Pillow

[tool.poetry.dev-dependencies]
