[project]
name = "VisuaLlama"
version = "v0.1"
description = "A conversational, object-counting assistant."
authors = [
    {name = "Daethyra (Daemon Carino)", email = "dev-daethyra@protonmail.com"},
]
dependencies = [
    "Pillow",
    "fastapi",
    "requests",
    "torch",
    "transformers",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "GNU AGPL"}
classifiers = [
    "Development Status :: v0.1 - Alpha",
    "Intended Audience :: Non-technical Users, Developers",
    "License :: OSI Approved :: Affero GNU GPL v3.0",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project.optional-dependencies]
tests = [
    "pytest",
    "pytest-asyncio",
    "pytest-env",
    "pytest-dotenv",
    "pytest-mock",
]
