version: "2.3"
services:
  visuallama:
    build:
      context: ../
      dockerfile: orchestration/Dockerfile
    # Uncomment the following lines for GPU support
    deploy:
        resources:
          reservations:
            devices:
              - capabilities:
                - gpu
    shm_size: "8gb"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    env_file:
      - ../.env
    environment:
      # Uncomment the following line for GPU support
      - NVIDIA_VISIBLE_DEVICES=all