name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "working" ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file orchestration/Dockerfile --tag VisuaLlama-test-deployment:$(date +%s)
