name: Test the orchestration process
# Author: Daethyra (Daemon Carino)

on:
  push:
    branches:
      - working

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test the dependency installation process
        run: |
          pdm install
          mv python.path .pdm-python
          mv .pdm.toml pdm.toml
